# Generated by Django 3.0.7 on 2020-06-18 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookflixapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='historial',
            field=models.ManyToManyField(to='bookflixapp.Libro'),
        ),
    ]
