# Generated by Django 3.0.7 on 2020-06-18 21:21

import bookflixapp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookflixapp', '0002_perfil_historial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='trailer',
        ),
        migrations.CreateModel(
            name='Trailer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('imagen', models.ImageField(null=True, upload_to=bookflixapp.models.Trailer.content_file_name)),
                ('texto', models.TextField(max_length=500)),
                ('libro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookflixapp.Libro')),
            ],
            options={
                'verbose_name_plural': 'Trailers',
            },
        ),
    ]
