# Generated by Django 3.0.7 on 2020-06-18 21:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bookflixapp', '0003_auto_20200618_1821'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trailer',
            options={'ordering': ['-creacion'], 'verbose_name_plural': 'Trailers'},
        ),
        migrations.AddField(
            model_name='trailer',
            name='creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Creacion'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trailer',
            name='libro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookflixapp.Libro'),
        ),
    ]
