# Generated by Django 3.0.7 on 2020-06-18 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookflixapp', '0004_auto_20200618_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trailer',
            name='libro',
        ),
        migrations.AddField(
            model_name='libro',
            name='trailer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookflixapp.Trailer'),
        ),
    ]
