# Generated by Django 3.0.7 on 2020-06-18 22:51

import bookflixapp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookflixapp', '0005_auto_20200618_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='trailer',
            field=models.ForeignKey(blank=True, default=2, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookflixapp.Trailer'),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='imagen',
            field=models.ImageField(default='default.jpg', null=True, upload_to=bookflixapp.models.Trailer.content_file_name),
        ),
    ]
