# Generated by Django 3.0.7 on 2020-06-18 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookflixapp', '0006_auto_20200618_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='trailer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bookflixapp.Trailer'),
        ),
    ]
