# Generated by Django 3.0.7 on 2020-06-18 23:03

import bookflixapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookflixapp', '0007_auto_20200618_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trailer',
            name='imagen',
            field=models.ImageField(default='default.jpg', null=True, upload_to=bookflixapp.models.Trailer.content_file_name, verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='texto',
            field=models.TextField(default='NONE', max_length=500, verbose_name='Texto'),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='titulo',
            field=models.CharField(default='NONE', max_length=200, verbose_name='Titulo'),
        ),
    ]
